# Generated by Django 4.2.20 on 2025-05-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimClass',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dim_class',
            },
        ),
        migrations.CreateModel(
            name='DimParent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('work', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'db_table': 'dim_parent',
            },
        ),
        migrations.CreateModel(
            name='DimStudent',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('avg_behaviour', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('avg_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dimparent')),
            ],
            options={
                'db_table': 'dim_student',
            },
        ),
        migrations.CreateModel(
            name='DimTeacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=100)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'db_table': 'dim_teacher',
            },
        ),
        migrations.CreateModel(
            name='FactAutismTeacherSurveyDataset',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.dimstudent')),
                ('Q1', models.IntegerField(blank=True, null=True)),
                ('Q2', models.IntegerField(blank=True, null=True)),
                ('Q3', models.IntegerField(blank=True, null=True)),
                ('Q4', models.IntegerField(blank=True, null=True)),
                ('Q5', models.IntegerField(blank=True, null=True)),
                ('Q6', models.IntegerField(blank=True, null=True)),
                ('Q7', models.IntegerField(blank=True, null=True)),
                ('Q8', models.IntegerField(blank=True, null=True)),
                ('Q9', models.IntegerField(blank=True, null=True)),
                ('Q10', models.IntegerField(blank=True, null=True)),
                ('Q11', models.IntegerField(blank=True, null=True)),
                ('Q12', models.IntegerField(blank=True, null=True)),
                ('Q13', models.IntegerField(blank=True, null=True)),
                ('Q14', models.IntegerField(blank=True, null=True)),
                ('Q15', models.IntegerField(blank=True, null=True)),
                ('Q16', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_autism_teacher_survey_dataset',
            },
        ),
        migrations.CreateModel(
            name='FactTeacherSurveyDataset',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.dimstudent')),
                ('Q1', models.IntegerField(blank=True, null=True)),
                ('Q2', models.IntegerField(blank=True, null=True)),
                ('Q3', models.IntegerField(blank=True, null=True)),
                ('Q4', models.IntegerField(blank=True, null=True)),
                ('Q5', models.IntegerField(blank=True, null=True)),
                ('Q6', models.IntegerField(blank=True, null=True)),
                ('Q7', models.IntegerField(blank=True, null=True)),
                ('Q8', models.IntegerField(blank=True, null=True)),
                ('Q9', models.IntegerField(blank=True, null=True)),
                ('Q10', models.IntegerField(blank=True, null=True)),
                ('Q11', models.IntegerField(blank=True, null=True)),
                ('Q12', models.IntegerField(blank=True, null=True)),
                ('Q13', models.IntegerField(blank=True, null=True)),
                ('Q14', models.IntegerField(blank=True, null=True)),
                ('Q15', models.IntegerField(blank=True, null=True)),
                ('Q16', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_teacher_survey_dataset',
            },
        ),
        migrations.CreateModel(
            name='FactWritingDataset',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('png_file', models.TextField(blank=True, null=True)),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dimstudent')),
            ],
            options={
                'db_table': 'fact_writing_dataset',
            },
        ),
        migrations.CreateModel(
            name='FactShapesDataset',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct', models.IntegerField(blank=True, null=True)),
                ('incorrect', models.IntegerField(blank=True, null=True)),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dimstudent')),
            ],
            options={
                'db_table': 'fact_shapes_dataset',
            },
        ),
        migrations.CreateModel(
            name='FactEmotionsDataset',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('happy', models.IntegerField(blank=True, null=True)),
                ('angry', models.IntegerField(blank=True, null=True)),
                ('sad', models.IntegerField(blank=True, null=True)),
                ('time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dimstudent')),
            ],
            options={
                'db_table': 'fact_emotions_dataset',
            },
        ),
    ]
