# Generated by Django 4.2.20 on 2025-05-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id_klasa', models.IntegerField()),
                ('nazwa', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id_nauczyciela', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('wyksztalcenie', models.CharField(max_length=50)),
                ('nauczany_przedmiot', models.CharField(max_length=100)),
                ('wiek', models.IntegerField()),
                ('plec', models.CharField(max_length=10)),
                ('nazwa_szkoly', models.CharField(max_length=100)),
                ('klasa', models.ManyToManyField(to='core.klasa')),
            ],
        ),
        migrations.CreateModel(
            name='Rodzic',
            fields=[
                ('id_rodzica', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('wiek', models.IntegerField()),
                ('zawod', models.CharField(max_length=100)),
                ('tel_kontaktowy', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id_ucznia', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('wiek', models.IntegerField()),
                ('opis_ucznia', models.CharField(max_length=100)),
                ('srednia_z_zachowania', models.DecimalField(decimal_places=1, max_digits=2)),
                ('srednia_ocen', models.DecimalField(decimal_places=1, max_digits=2)),
                ('podejrzenie_ADHD', models.CharField(max_length=100)),
                ('id_rodzica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rodzic')),
                ('klasa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.klasa')),
            ],
        ),
        migrations.CreateModel(
            name='WynikiKwestionariuszy',
            fields=[
                ('id_wynik_kwest', models.IntegerField(primary_key=True, serialize=False)),
                ('id_kwestionariusza', models.IntegerField()),
                ('odp_1', models.IntegerField()),
                ('odp_2', models.IntegerField()),
                ('odp_3', models.IntegerField()),
                ('odp_4', models.IntegerField()),
                ('odp_5', models.IntegerField()),
                ('id_nauczyciela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nauczyciel')),
                ('id_ucznia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uczen')),
            ],
        ),
        migrations.CreateModel(
            name='WynikiGier',
            fields=[
                ('id_wyniku', models.IntegerField(primary_key=True, serialize=False)),
                ('id_gry', models.IntegerField()),
                ('czas_wykonania', models.IntegerField()),
                ('wynik_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wynik_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wynik_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wynik_4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wynik_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wynik_6', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_ucznia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uczen')),
            ],
        ),
        migrations.CreateModel(
            name='WritingsDataset',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uczen')),
            ],
        ),
        migrations.CreateModel(
            name='ShapesDataset',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uczen')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionsDataset',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('happy', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uczen')),
            ],
        ),
    ]
